---
title: "Lab 4"
output: html_notebook
---

Data Read

```{r}
data <- read.csv('Birth Data.csv')
```

Check Data

```{r}
head(data)
tail(data)
summary(data)
names(data)
ncol(data)
nrow(data)
```

Check Data Types

```{r}
class(data)
```

```{r}
class(data$X2017)
```

Data Wrangling

```{r}
data$X2017

as.numeric(data$X2017)
```

```{r}
as.numeric("31234")

as.numeric("31,234")
```

```{r}
as.numeric(gsub(",", "", data$X2017))
```

```{r}
data$X2017 = as.numeric(gsub(",", "", data$X2017))
data$X2017
```

Bar Plot

```{r}
barplot(data$X2017)
```

```{r}
barplot(data$X2017, names=data$Region, las=3)
```

```{r}
data$X2018 = as.numeric(gsub(",", "", data$X2018))
matrix = rbind(data$X2017, data$X2018)
```

```{r}
barplot(matrix, beside = TRUE, horiz = TRUE, names = data$Region, col = c("blue", "green"), main = "Births in Different Regions of Australia",
        xlab = "Number of Births", ylab = "Region", las = 1)

legend("topright", legend = c("2017", "2018"), fill = c("blue", "green"))
```

Line Plot

```{r}
data$X2019 = as.numeric(gsub(",", "", data$X2019))
data$X2020 = as.numeric(gsub(",", "", data$X2020))
```

```{r}
plot(c(2017:2020), data[2, 2:5], type="o", col="red", xlab="Year", ylab="Birth number", main="The number of births in Victoria")
```

```{r}
plot(c(2017:2020), data[2, 2:5], type="o", col="red", xaxt="n", xlab="Year", ylab="Birth number", main="The number of births in Victoria")

axis(1,at=c("2017", "2018", "2019", "2020"))
```

```{r}
plot(2017:2020, data[1, 2:5], type = "l", xlab = "Year", ylab = "Number of Births",
     main = "Number of Births in Each State of Australia (2017-2020)", xaxt = "n", ylim = range(c(1:110000)))

# Add lines for each state
for (i in 2:8) {
  lines(2017:2020, data[i, 2:5], type = "o", pch = i, col = i)
}

axis(1,at=c("2017", "2018", "2019", "2020"))

legend("topright", legend = data$Region, col = 1:8, pch = 1:8, title = "States")
```
